format:
  html:
    css:
      - "../../css/styles.css"
      - "../../css/article.css"
    page-layout: full
    fig-align: center
    include-before-body: "../navbar.html"
    include-after-body: "../footer.html"
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">