format:
  html:
    css:
      - "../../css/styles.css"
      - "../../css/article.css"
    page-layout: full
    fig-align: center
    include-before-body: "../navbar.html"
    include-after-body: "../footer.html"
    favicon: 
    include-in-header:
      - text: |
          <link rel = "shortcut icon" href = "../../../assets/favicon.ico" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
          <!-- Google tag (gtag.js) -->
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-8ZGMYX2VV4"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-8ZGMYX2VV4');
          </script>