name: Deploy to development

on:
  workflow_dispatch:

jobs:
  minify:
    runs-on: ubuntu-latest
    env:
      GIT_AUTH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: git checkout -B dev

      - name: Minify .css
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: true
          directory: "css"

      - name: Minify .js
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: true
          directory: "js"

      - name: Commit minified files to dev
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "GHA: Minified .css and .js"
          create_branch: true
          branch: dev
          push_options: '--force'

  quarto:
    needs: minify
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Install curl
        run: |
          sudo apt -y install libcurl4-openssl-dev

      - name: Cache R packages"
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R Packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install Quarto and render
        uses: pommevilla/quarto-render@main

      - name: Commit rendered files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "GHA: Rendered quarto documents"
          branch: dev
          push_options: '--force'
